# Generated by Django 2.0.5 on 2018-06-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pyetjet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=150)),
                ('A1', models.CharField(max_length=100)),
                ('A2', models.CharField(max_length=100)),
                ('A3', models.CharField(max_length=100)),
                ('A4', models.CharField(max_length=100)),
                ('As', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quizet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emri', models.CharField(max_length=50)),
                ('pershkrimi', models.CharField(max_length=150)),
            ],
        ),
    ]
